//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookManager_API.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class BorrowBook
    {
        public decimal ID { get; set; }
        public int BookID { get; set; }
        public string AdminNationalNumber { get; set; }
        public int UserID { get; set; }
        public System.DateTime PickDate { get; set; }
        public System.DateTime ReturnDate { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Library Library { get; set; }
        public virtual User User { get; set; }
    }
}
